version: '3'

networks:
  app:

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - app

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
    - app
